# Generated by Django 5.2.9 on 2025-12-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='头像图片地址（URL）', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='good_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='好评率，例如 98.50 表示 98.50%', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='邮箱是否已通过验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='手机号是否已通过验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='用户昵称，用于前端展示', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='手机号（可选）', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', '普通买家'), ('seller', '普通卖家'), ('both', '买家 & 卖家')], default='both', help_text='用户在平台中的角色类型', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='trade_count',
            field=models.PositiveIntegerField(default=0, help_text='累计成功交易订单数'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='用户信息最近更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='平台账户余额，用于收款 / 退款等', max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(default=100, help_text='平台内部信用积分，初始值可设为 100'),
        ),
    ]
