# Generated by Django 5.2.9 on 2025-12-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_good_rate_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', '普通买家'), ('seller', '普通卖家'), ('admin', '买家 & 卖家')], default='buyer', help_text='用户在平台中的角色类型', max_length=10),
        ),
    ]
