# Generated by Django 5.2.9 on 2025-12-14 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类名称，如手机、平板', max_length=50)),
                ('code', models.CharField(blank=True, help_text='分类编码，便于前端或运营配置（可选）', max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='分类说明，例如主要面向的设备类型、典型品牌等')),
                ('icon', models.URLField(blank=True, help_text='分类图标 URL（可选）', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.URLField(blank=True, help_text='品牌 Logo 地址（可选）', null=True)),
                ('description', models.TextField(blank=True, help_text='品牌介绍或备注说明')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='市场基准回收价（可根据官方或历史数据确定）', max_digits=10)),
                ('release_date', models.DateField(blank=True, help_text='上市日期（用于估价时判断新旧程度）', null=True)),
                ('storage_spec', models.CharField(blank=True, help_text='存储规格，如 128GB / 256GB（可选）', max_length=50)),
                ('color', models.CharField(blank=True, help_text='官方主推颜色，如 星光色、远峰蓝（可选）', max_length=30)),
                ('is_discontinued', models.BooleanField(default=False, help_text='是否停产，用于估价与推荐策略')),
                ('official_url', models.URLField(blank=True, help_text='官方产品介绍链接（可选）', null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_price', models.DecimalField(decimal_places=2, help_text='系统估价（由估价引擎自动计算）', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='卖家实际售价', max_digits=10)),
                ('status', models.CharField(choices=[('draft', '草稿/估价中'), ('on_sale', '上架中'), ('locked', '交易中/已锁定'), ('sold', '已售出'), ('cancelled', '已下架')], default='draft', max_length=20)),
                ('quality_grade', models.CharField(choices=[('A', '准新 / 轻微使用痕迹'), ('B', '正常使用痕迹'), ('C', '明显磨损但功能正常'), ('D', '功能/外观存在明显问题')], default='B', help_text='成色等级，便于前端筛选展示', max_length=1)),
                ('location', models.CharField(blank=True, help_text='设备所在城市/地区，如 深圳市 南山区', max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='浏览次数（可用于推荐与热度排序）')),
                ('favorite_count', models.PositiveIntegerField(default=0, help_text='被收藏次数')),
                ('is_recommended', models.BooleanField(default=False, help_text='是否为平台推荐商品')),
                ('condition_data', models.JSONField(default=dict, help_text='估价时用户选择的配置与成色快照（JSON）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='商品创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='商品最近更新时间')),
                ('device_model', models.ForeignKey(help_text='关联的设备型号', on_delete=django.db.models.deletion.PROTECT, to='market.devicemodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(help_text='订单编号，可使用 UUID 等规则生成', max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='订单金额（应付金额）', max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', '待支付'), ('paid', '已支付/待发货'), ('shipped', '已发货/待收货'), ('inspecting', '验机中'), ('completed', '已完成'), ('refunded', '已退款/取消')], default='pending_payment', max_length=20)),
                ('payment_method', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('balance', '平台余额')], default='balance', help_text='支付方式（可根据项目实际调整）', max_length=20)),
                ('shipping_code', models.CharField(blank=True, help_text='物流单号（可选）', max_length=50, null=True)),
                ('logistics_company', models.CharField(blank=True, help_text='物流公司名称，如 顺丰 / 圆通', max_length=50)),
                ('receiver_name', models.CharField(blank=True, help_text='收货人姓名', max_length=50)),
                ('receiver_phone', models.CharField(blank=True, help_text='收货人手机号', max_length=20)),
                ('receiver_address', models.CharField(blank=True, help_text='收货地址', max_length=255)),
                ('pay_time', models.DateTimeField(blank=True, help_text='支付时间', null=True)),
                ('ship_time', models.DateTimeField(blank=True, help_text='发货时间', null=True)),
                ('complete_time', models.DateTimeField(blank=True, help_text='订单完成时间', null=True)),
                ('cancel_time', models.DateTimeField(blank=True, help_text='订单取消/退款时间', null=True)),
                ('buyer_message', models.TextField(blank=True, help_text='买家留言')),
                ('seller_message', models.TextField(blank=True, help_text='卖家备注（仅后台可见）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='订单创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='订单最近更新时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(help_text='关联的商品，完成交易后商品即售出', on_delete=django.db.models.deletion.PROTECT, to='market.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(help_text='加密/随机命名后的 jpg 文件名，如 3b2f...e9.jpg', max_length=255)),
                ('original_name', models.CharField(blank=True, help_text='原始文件名（可选）', max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0, help_text='文件大小（字节，可选）')),
                ('is_main', models.BooleanField(default=False, help_text='是否为主图')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='图片排序，数值越小越靠前')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='上传时间')),
                ('product', models.ForeignKey(blank=True, help_text='可先上传图片不绑定商品，后续再关联到草稿商品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.product')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='上传者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_product_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValuationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField(default=1.0, help_text='权重（用于估价算法加权）')),
                ('is_required', models.BooleanField(default=True, help_text='该估价选项是否为必选项')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='前端展示顺序，数值越小越靠前')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValuationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('depreciation_rate', models.FloatField(help_text='折旧率，例如 0.05 代表扣减 5%')),
                ('score', models.IntegerField(default=0, help_text='可选的评分值，用于统计或规则引擎（例如好=3，一般=1）')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='market.valuationoption')),
            ],
        ),
    ]
