# Generated by Django 5.2.9 on 2025-12-11 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valuationoption',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, help_text='品牌介绍或备注说明'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.URLField(blank=True, help_text='品牌 Logo 地址（可选）', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, help_text='分类编码，便于前端或运营配置（可选）', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='分类说明，例如主要面向的设备类型、典型品牌等'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.URLField(blank=True, help_text='分类图标 URL（可选）', null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='color',
            field=models.CharField(blank=True, help_text='官方主推颜色，如 星光色、远峰蓝（可选）', max_length=30),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='是否停产，用于估价与推荐策略'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='official_url',
            field=models.URLField(blank=True, help_text='官方产品介绍链接（可选）', null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='storage_spec',
            field=models.CharField(blank=True, help_text='存储规格，如 128GB / 256GB（可选）', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_message',
            field=models.TextField(blank=True, help_text='买家留言'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_time',
            field=models.DateTimeField(blank=True, help_text='订单取消/退款时间', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, help_text='订单完成时间', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_company',
            field=models.CharField(blank=True, help_text='物流公司名称，如 顺丰 / 圆通', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(blank=True, help_text='支付时间', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('balance', '平台余额')], default='balance', help_text='支付方式（可根据项目实际调整）', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_address',
            field=models.CharField(blank=True, help_text='收货地址', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(blank=True, help_text='收货人姓名', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(blank=True, help_text='收货人手机号', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_message',
            field=models.TextField(blank=True, help_text='卖家备注（仅后台可见）'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_time',
            field=models.DateTimeField(blank=True, help_text='发货时间', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, help_text='被收藏次数'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='是否为平台推荐商品'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, help_text='设备所在城市/地区，如 深圳市 南山区', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_grade',
            field=models.CharField(choices=[('A', '准新 / 轻微使用痕迹'), ('B', '正常使用痕迹'), ('C', '明显磨损但功能正常'), ('D', '功能/外观存在明显问题')], default='B', help_text='成色等级，便于前端筛选展示', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='商品最近更新时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='浏览次数（可用于推荐与热度排序）'),
        ),
        migrations.AddField(
            model_name='valuationchoice',
            name='score',
            field=models.IntegerField(default=0, help_text='可选的评分值，用于统计或规则引擎（例如好=3，一般=1）'),
        ),
        migrations.AddField(
            model_name='valuationoption',
            name='is_required',
            field=models.BooleanField(default=True, help_text='该估价选项是否为必选项'),
        ),
        migrations.AddField(
            model_name='valuationoption',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='前端展示顺序，数值越小越靠前'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='市场基准回收价（可根据官方或历史数据确定）', max_digits=10),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='release_date',
            field=models.DateField(blank=True, help_text='上市日期（用于估价时判断新旧程度）', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='订单金额（应付金额）', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='订单创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(help_text='订单编号，可使用 UUID 等规则生成', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.OneToOneField(help_text='关联的商品，完成交易后商品即售出', on_delete=django.db.models.deletion.PROTECT, to='market.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_code',
            field=models.CharField(blank=True, help_text='物流单号（可选）', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='订单最近更新时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition_data',
            field=models.JSONField(default=dict, help_text='估价时用户选择的配置与成色快照（JSON）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='商品创建时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_model',
            field=models.ForeignKey(help_text='关联的设备型号', on_delete=django.db.models.deletion.PROTECT, to='market.devicemodel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, help_text='系统估价（由估价引擎自动计算）', max_digits=10),
        ),
        migrations.AlterField(
            model_name='valuationchoice',
            name='depreciation_rate',
            field=models.FloatField(help_text='折旧率，例如 0.05 代表扣减 5%'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='图片 URL（前端或对象存储地址）')),
                ('is_main', models.BooleanField(default=False, help_text='是否为主图')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='图片排序，数值越小越靠前')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
